### ISSUE TITLE
kde-plasma/kscreenlocker: no-SUID-no-GUID patch fails

### ISSUE THREAD

**Issue by WInf9FH** [gentoo/kde#636] opened 2016-03-19 10:58 UTC
Hi,

applying the no-SUID-no-GUID patch fails on my system:

 Source unpacked in /var/tmp/portage/kde-plasma/kscreenlocker-9999/work
 Preparing source in /var/tmp/portage/kde-plasma/kscreenlocker-9999/work/kscreenlocker-9999 ...
 * Applying kscreenlocker-5.4.90-no-SUID-no-GUID.patch ...
1 out of 1 hunk FAILED -- saving rejects to file kcheckpass/CMakeLists.txt.rej
 [ !! ]
 * ERROR: kde-plasma/kscreenlocker-9999::kde failed (prepare phase):
 *   patch -p1  failed with /var/lib/layman/kde/kde-plasma/kscreenlocker/files/kscreenlocker-5.4.90-no-SUID-no-GUID.patch

It looks to me like the patch itself still looks good, maybe just the place in the file changed to much.

Regards and thanks for the good work,
Frank

**Comment by johu** [comment] 2016-03-19 11:41
Duplicate of https://bugs.gentoo.org/show_bug.cgi?id=577754

**Closed by johu** 2016-03-19 11:41 UTC
