### ISSUE TITLE
=kde-apps/mailcommon-15.12.1:5::kde should deps not on =media-libs/phonon-4.7.2

### ISSUE THREAD

**Issue by init6** [gentoo/kde#567] opened 2016-01-20 09:53 UTC
**=kde-apps/mailcommon-15.12.1:5::kde** should deps not on **=media-libs/phonon-4.7.2**

with **=media-libs/phonon-4.7.2** failed to build with:

    # emerge -1 =kde-apps/mailcommon-15.12.1:5::kde

    These are the packages that would be merged, in order:

    2016-01-20 04:32:43: Calculating dependencies /
    2016-01-20 04:33:19: Adding root packages |
    2016-01-20 04:33:19: Processing dependencies /
    2016-01-20 04:33:21: Checking for slot conflicts  
    2016-01-20 04:33:21: Trying to accept blocker conflicts   
    2016-01-20 04:33:21: Resolving slot conflicts for complete graph   
    2016-01-20 04:33:21: Processing slot conflicts   
    2016-01-20 04:33:21: Triggering slot operator reinstalls   
    2016-01-20 04:33:21: Validating blockers  \
    2016-01-20 04:33:27: Checking for blocker conflicts  
    2016-01-20 04:33:27: Checking for rebuild triggers  
    2016-01-20 04:33:27: Checking if restart is needed  
    2016-01-20 04:33:27: Checking if we have to prune rebuilds  
    2016-01-20 04:33:27: Checking if restart is needed  
    2016-01-20 04:33:27: Checking for parameters that change behavior  
    2016-01-20 04:33:27: Checking for changes that are needed  
    2016-01-20 04:33:27: Done resolving!... done!
    [ebuild  N    ~] kde-apps/mailcommon-15.12.1:5::kde  USE="-debug -designer" 0 KiB

    Total: 1 package (1 new), Size of downloads: 0 KiB

    >>> Verifying ebuild manifests
    >>> Running pre-merge checks for kde-apps/mailcommon-15.12.1

    >>> Emerging (1 of 1) kde-apps/mailcommon-15.12.1::kde
    * kdepim-15.12.1.tar.xz SHA256 SHA512 WHIRLPOOL size ;-) ...                             [ ok ]
    >>> Unpacking source...
    >>> Unpacking kdepim-15.12.1.tar.xz to /var/tmp/portage/kde-apps/mailcommon-15.12.1/work
    >>> Source unpacked in /var/tmp/portage/kde-apps/mailcommon-15.12.1/work
    >>> Preparing source in /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/kdepim-15.12.1/mailcommon ...
    * Applying mailcommon-15.12.0-find-qt5designer.patch ...                                 [ ok ]
    >>> Source prepared.
    >>> Configuring source in /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/kdepim-15.12.1/mailcommon ...
    >>> Working in BUILD_DIR: "/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build"
    cmake --no-warn-unused-cli -C /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTING=OFF -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DCMAKE_DISABLE_FIND_PACKAGE_Qt5Designer=ON -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_INSTALL_DO_STRIP=OFF -DCMAKE_USER_MAKE_RULES_OVERRIDE=/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build/gentoo_toolchain.cmake  /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/kdepim-15.12.1/mailcommon
    Not searching for unused variables given on the command line.
    loading initial cache file /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build/gentoo_common_config.cmake
    -- The C compiler identification is GNU 4.9.3
    -- The CXX compiler identification is GNU 4.9.3
    -- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
    -- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
    -- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for __GLIBC__
    -- Looking for __GLIBC__ - found
    -- Performing Test _OFFT_IS_64BIT
    -- Performing Test _OFFT_IS_64BIT - Success
    -- Found Gettext: /usr/bin/msgmerge (found version "0.19.4") 
    -- Found PythonInterp: /usr/bin/python (found version "3.4.3") 
    -- Boost version: 1.56.0
    -- Looking for dgettext
    -- Looking for dgettext - found
    -- Found Gettext: built in libc
    -- Found Libical version 1.0
    -- Found LibIcal: /usr/lib64/libical.so;/usr/lib64/libicalss.so (found suitable version "1.0", minimum required is "0.42") 
    -- checking for module 'libsasl2'
    --   found libsasl2, version 2.1.26
    -- Found Sasl2: /usr/lib64/libsasl2.so (found version "2.1.26") 
    -- Found Ldap: /usr/lib64/libldap.so;/usr/lib64/liblber.so (found version "2.4.38") 
    -- 
    -- The following REQUIRED packages have been found:

    * ECM (required version >= 5.16.0)
    * Qt5Gui (required version >= 5.5.1)
    * KF5Akonadi (required version >= 5.1)
    * Qt5Widgets
    * Qt5Test
    * Qt5UiPlugin (required version >= 5.5.1)
    * Qt5UiTools
    * Qt5 (required version >= 5.4.0)
    * Gettext
    * PythonInterp
    * KF5I18n (required version >= 5.16.0)
    * KF5Mime (required version >= 4.87.0)
    * KF5AkonadiMime (required version >= 5.1)
    * KF5Codecs (required version >= 5.16.0)
    * KF5IconThemes (required version >= 5.16.0)
    * KF5Archive (required version >= 5.16.0)
    * KF5ItemViews (required version >= 5.16.0)
    * KF5WindowSystem (required version >= 5.16.0)
    * KF5XmlGui (required version >= 5.16.0)
    * Qt5WebKit (required version >= 5.5.1)
    * KF5MessageViewer (required version >= 5.1)
    * KF5TemplateParser (required version >= 5.1)
    * KF5Libkdepim (required version >= 5.1)
    * KF5PimCommon (required version >= 5.1)
    * KF5MessageComposer (required version >= 5.1)
    * KF5MessageCore (required version >= 5.1)
    * KF5MailImporter (required version >= 5.1)
    * KF5MailTransport (required version >= 4.78.0)
    * KF5Ldap (required version >= 4.80.0)
    * Phonon4Qt5
    * Xsltproc , XSLT processor from libxslt
    Required to generate D-Bus interfaces for all Akonadi resources.

    -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
    -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
    -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
    -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
    -- Performing Test COMPILER_HAS_DEPRECATED_ATTR
    -- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
    -- <<< Gentoo configuration >>>
    Build type      Gentoo
    Install path    /usr
    Compiler flags:
    C               -mtune=generic -O2 -pipe  -std=iso9899:1990 -fno-common -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wmissing-format-attribute -Wwrite-strings -Werror=implicit-function-declaration
    C++             -mtune=generic -O2 -pipe  -std=c++0x -fno-exceptions -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -pedantic
    Linker flags:
    Executable      -Wl,--enable-new-dtags  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--sort-common -Wl,--as-needed
    Module          -Wl,--no-undefined -Wl,--fatal-warnings -Wl,--enable-new-dtags  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--sort-common -Wl,--as-needed
    Shared          -Wl,--no-undefined -Wl,--fatal-warnings -Wl,--enable-new-dtags  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--sort-common -Wl,--as-needed

    -- Configuring done
    -- Generating done
    -- Build files have been written to: /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build
    >>> Source configured.
    >>> Compiling source in /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/kdepim-15.12.1/mailcommon ...
    >>> Working in BUILD_DIR: "/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build"
    make -j3 -l2 VERBOSE=1 
    /usr/bin/cmake -H/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/kdepim-15.12.1/mailcommon -B/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build --check-build-system CMakeFiles/Makefile.cmake 0
    /usr/bin/cmake -E cmake_progress_start /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build/CMakeFiles /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build/CMakeFiles/progress.marks
    make -f CMakeFiles/Makefile2 all
    make[1]: Entering directory '/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build'
    make -f src/CMakeFiles/KF5MailCommon_automoc.dir/build.make src/CMakeFiles/KF5MailCommon_automoc.dir/depend
    make[2]: Entering directory '/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build'
    cd /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/kdepim-15.12.1/mailcommon /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/kdepim-15.12.1/mailcommon/src /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build/src /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build/src/CMakeFiles/KF5MailCommon_automoc.dir/DependInfo.cmake --color=
    Dependee "/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build/src/CMakeFiles/KF5MailCommon_automoc.dir/DependInfo.cmake" is newer than depender "/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build/src/CMakeFiles/KF5MailCommon_automoc.dir/depend.internal".
    Dependee "/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build/src/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build/src/CMakeFiles/KF5MailCommon_automoc.dir/depend.internal".

    (CUT)

    [ 65%] Building CXX object src/CMakeFiles/KF5MailCommon.dir/filter/filteractions/filteractionplaysound.cpp.o
    cd /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build/src && /usr/bin/x86_64-pc-linux-gnu-g++  -DKCOREADDONS_LIB -DKF5MailCommon_EXPORTS -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_USE_FAST_OPERATOR_PLUS -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_XML_LIB -DTRANSLATION_DOMAIN=\"libmailcommon\" -D_GNU_SOURCE -D_LARGEFILE64_SOURCE   -DQT_NO_DEBUG -DNDEBUG -mtune=generic -O2 -pipe  -std=c++0x -fno-exceptions -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -pedantic -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -I/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build/src -I/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/kdepim-15.12.1/mailcommon/src -I/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/kdepim-15.12.1/mailcommon/src/search -isystem /usr/include/KF5/AkonadiCore -isystem /usr/include/KF5 -isystem /usr/include/KF5/akonadi/private -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/KF5/KItemModels -isystem /usr/include/qt5/QtGui -isystem /usr/include/KF5/Akonadi/KMime -isystem /usr/include/KF5/akonadi/kmime -isystem /usr/include/KF5/MessageComposer -isystem /usr/include/KF5/messagecomposer -isystem /usr/include/KF5/KMime -isystem /usr/include/KF5/MessageCore -isystem /usr/include/KF5/messagecore -isystem /usr/include/KF5/PimCommon -isystem /usr/include/KF5/pimcommon -isystem /usr/include/KF5/KIMAP -isystem /usr/include/KF5/KTextWidgets -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/KF5/SonnetUi -isystem /usr/include/KF5/KI18n -isystem /usr/include/KF5/AkonadiWidgets -isystem /usr/include/KF5/KContacts -isystem /usr/include/KF5/Akonadi/Contact -isystem /usr/include/KF5/akonadi/contact -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/KF5/KIOCore -isystem /usr/include/KF5/KService -isystem /usr/include/KF5/KConfigCore -isystem /usr/include/KF5/KConfigWidgets -isystem /usr/include/KF5/KCodecs -isystem /usr/include/KF5/KWidgetsAddons -isystem /usr/include/KF5/KConfigGui -isystem /usr/include/qt5/QtXml -isystem /usr/include/KF5/KAuth -isystem /usr/include/KF5/KIdentityManagement -isystem /usr/include/KF5/KIdentityManagement/kidentitymanagement -isystem /usr/include/KF5/KPIMTextEdit -isystem /usr/include/KF5/Libkleo -isystem /usr/include/KF5/libkleo -isystem /usr/include/KF5/qgpgme -isystem /usr/include/KF5/gpgme++ -isystem /usr/include/KF5/Libkdepim -isystem /usr/include/KF5/libkdepim -isystem /usr/include/KF5/MessageViewer -isystem /usr/include/KF5/messageviewer -isystem /usr/include/KF5/KDEWebKit -isystem /usr/include/qt5/QtWebKitWidgets -isystem /usr/include/qt5/QtWebKit -isystem /usr/include/KF5/MailImporter -isystem /usr/include/KF5/mailimporter -isystem /usr/include/KF5/TemplateParser -isystem /usr/include/KF5/templateparser -isystem /usr/include/KF5/MailTransport -isystem /usr/include/KF5/MailTransport/mailtransport -isystem /usr/include/KF5/KWallet -isystem /usr/include/KF5/KXmlGui -isystem /usr/include/qt5/QtDBus -isystem /usr/include/KF5/KIOWidgets -isystem /usr/include/KF5/KJobWidgets -isystem /usr/include/KF5/KCompletion -isystem /usr/include/KF5/KWindowSystem -isystem /usr/include/KF5/KIconThemes -isystem /usr/include/KF5/KArchive -isystem /usr/include/KF5/KItemViews -isystem /usr/include/KF5/KLDAP    -fexceptions -fPIC -o CMakeFiles/KF5MailCommon.dir/filter/filteractions/filteractionplaysound.cpp.o -c /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/kdepim-15.12.1/mailcommon/src/filter/filteractions/filteractionplaysound.cpp
    /var/tmp/portage/kde-apps/mailcommon-15.12.1/work/kdepim-15.12.1/mailcommon/src/filter/filteractions/filteractionplaysound.cpp:24:32: fatal error: phonon/mediaobject.h: No such file or directory
    #include <phonon/mediaobject.h>
            ^
    compilation terminated.
    src/CMakeFiles/KF5MailCommon.dir/build.make:1944: recipe for target 'src/CMakeFiles/KF5MailCommon.dir/filter/filteractions/filteractionplaysound.cpp.o' failed
    make[2]: *** [src/CMakeFiles/KF5MailCommon.dir/filter/filteractions/filteractionplaysound.cpp.o] Error 1
    make[2]: Leaving directory '/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build'
    CMakeFiles/Makefile2:152: recipe for target 'src/CMakeFiles/KF5MailCommon.dir/all' failed
    make[1]: *** [src/CMakeFiles/KF5MailCommon.dir/all] Error 2
    make[1]: Leaving directory '/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build'
    Makefile:127: recipe for target 'all' failed
    make: *** [all] Error 2
    * ERROR: kde-apps/mailcommon-15.12.1::kde failed (compile phase):
    *   emake failed
    * 
    * If you need support, post the output of `emerge --info '=kde-apps/mailcommon-15.12.1::kde'`,
    * the complete build log and the output of `emerge -pqv '=kde-apps/mailcommon-15.12.1::kde'`.
    * The complete build log is located at '/var/log/portage/build/kde-apps/mailcommon-15.12.1:20160120-043331.log'.
    * For convenience, a symlink to the build log is located at '/var/tmp/portage/kde-apps/mailcommon-15.12.1/temp/build.log'.
    * The ebuild environment file is located at '/var/tmp/portage/kde-apps/mailcommon-15.12.1/temp/environment'.
    * Working directory: '/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/mailcommon-15.12.1_build'
    * S: '/var/tmp/portage/kde-apps/mailcommon-15.12.1/work/kdepim-15.12.1/mailcommon'

    >>> Failed to emerge kde-apps/mailcommon-15.12.1, Log file:

    >>>  '/var/log/portage/build/kde-apps/mailcommon-15.12.1:20160120-043331.log'

with =media-libs/phonon-4.8.3-r1 build fine for my.

**Comment by kensington** [comment] 2016-01-22 10:07
I'm not sure I understand - do you mean mailcommon requires a newer version of phonon? 4.7.2 installs phonon/mediaobject.h locally.

**Comment by init6** [comment] 2016-01-22 10:10
@kensington **=kde-apps/mailcommon-15.12.1** with **=media-libs/phonon-4.7.2** failed to build see log ^ with **=media-libs/phonon-4.8.3-r1** build fine.

**Comment by johu** [comment] 2016-03-15 09:38
Duplicate of bug https://bugs.gentoo.org/show_bug.cgi?id=573460. Please proceed there.

**Closed by johu** 2016-03-15 09:38 UTC
