### ISSUE TITLE
Compile kde-plasma/ksysguard-5.5.3 failed.

### ISSUE THREAD

**Issue by OwenChia** [gentoo/kde#554] opened 2016-01-08 09:48 UTC
build.log is here:
/usr/lib64/libQt5Gui.so.5.6.0 /usr/lib64/libQt5Core.so.5.6.0 -Wl,-rpath,/var/tmp/portage/kde-plasma/ksysguard-5.5.3/work/ksysguard-5.5.3_build/gui: 
/usr/lib64/libQt5WebKit.so.5: undefined reference to `QWindowSystemInterface::registerTouchDevice(QTouchDevice*)'
collect2: error: ld returned 1 exit status
gui/CMakeFiles/ksysguard.dir/build.make:120: recipe for target 'gui/ksysguard' failed
make[2]: *** [gui/ksysguard] Error 1
make[2]: Leaving directory '/var/tmp/portage/kde-plasma/ksysguard-5.5.3/work/ksysguard-5.5.3_build'
CMakeFiles/Makefile2:292: recipe for target 'gui/CMakeFiles/ksysguard.dir/all' failed
make[1]: *** [gui/CMakeFiles/ksysguard.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/kde-plasma/ksysguard-5.5.3/work/ksysguard-5.5.3_build'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
 * ERROR: kde-plasma/ksysguard-5.5.3::kde failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=kde-plasma/ksysguard-5.5.3::kde'`,
 * the complete build log and the output of `emerge -pqv '=kde-plasma/ksysguard-5.5.3::kde'`.
 * The complete build log is located at '/var/tmp/portage/kde-plasma/ksysguard-5.5.3/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/kde-plasma/ksysguard-5.5.3/temp/environment'.
 * Working directory: '/var/tmp/portage/kde-plasma/ksysguard-5.5.3/work/ksysguard-5.5.3_build'
 * S: '/var/tmp/portage/kde-plasma/ksysguard-5.5.3/work/ksysguard-5.5.3'
```
Maybe I should upgrade qtwebkit's version to 5.6? Now is 5.5.1.

**Comment by a17r** [comment] 2016-01-08 17:33
Reason: There is no qtwebkit-5.6

**Comment by yellowhat** [comment] 2016-01-10 20:45
Same problem for me.

**Comment by OwenChia** [comment] 2016-01-11 13:55
@yellowhat Try downgrade the qt's version to 5.5.1, it's work for me.

**Comment by yellowhat** [comment] 2016-01-11 19:20
I was on qt overlay [5.6.0-beta], now I am on 5.5.1 and same problem.

**Comment by a17r** [comment] 2016-01-12 00:09
sure it's actually the same error? did you rebuild qtwebkit as well or just downgrade others to 5.5.1?

**Comment by OwenChia** [comment] 2016-01-12 04:32
@yellowhat Maybe you need rebuild some package in category kde-plasma which already build with qt 5.6.0_beta. Like this:
```
emerge -1 $(find /var/db/pkg/ -mindepth 2 -maxdepth 2 -name \*-5.5.3|awk -F \/ '{printf "=%s/%s\n", $5, $6}') 
```

**Comment by yellowhat** [comment] 2016-01-12 19:36
Remerging packages in kde-plasma, solved.
Thanks to OwenChia

**Comment by johu** [comment] 2016-03-15 09:21
Thanks, closing then.

**Comment by johu** [comment] 2016-03-15 09:23
Now

**Comment by johu** [comment] 2016-03-15 09:36
Thanks. Closing then.

**Comment by johu** [comment] 2016-03-15 22:07
Nextr try to close it then...

**Comment by OwenChia** [comment] 2016-03-16 01:03
@johu 
I just clicked the 'close issues' button, but it doesn't work.

**Comment by johu** [comment] 2016-03-16 07:40
@OwenChia same for me

**Comment by johu** [comment] 2016-03-23 16:02
Just for the record: The cause for non closing github issue was the full build log comment. I shortened it and closing works like a charm again.

**Closed** 2016-03-23 16:01 UTC
